apiVersion: v1
kind: Service
metadata:
    name: "ghost-de5c"
    labels:
        app: "ghost-de5c"
spec:
    type: LoadBalancer
    ports:
    - port: 2368
      targetPort: 2368
      protocol: TCP
      name: http
    selector:
        app: "ghost-de5c"